language: node_js
node_js:
- node
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
deploy:
  provider: releases
  api_key:
    secure: DMOqqz9M4Cs5AQ0W9D3fWkVWoIuQpPxMPg7j0/luLumY85BGoSrTiQeE6tYZ2YZt9GbHHLH0vbx6Uqk7SqW2X8uCXUnitA82m/Av/jJ0ui0D8zxBbRZp6+RUdboYpS/Y8e1+TPDPllkoJk+BNOAX1uk+lsSPJv3uxMfXqNybrjAxd7MtbeljTdt8qItTiHx5N/rg6ACyd1BBVDgKzrrexlS2DbvJQzD4emBHPWjFBL2UxCWw6kItPx6CjqlBADlbREvTWVPc7XFNFTR8PQ4UXaFMAsiqBoEKZsTLum6KSKGsuSyRNil52B0fy3Qmsy5zu+nJD7qPAIkzOnLdjsUH/6f/vPcN8aVSdendVMJPTl+6YOSUyDeg2I2a5JHTju4xTjJq+2I+pGrI1qrZCjkPH75yICOQNMIKFSqwbWgQFdM3x2LfMYyhygu+00y0II3ccWqQK8E9+XVxkyvNInspHNM5KAZnMV3aCrILXjgcZBHGlw8w/5ZhJnNnwe/lhfaov8ouedlfCMkMOcb4gDToE5ackMxz3fD31b+uxiIzUZYymb+JFGwmrAk9qFCk8m1wru186IbyAhPv0fciC3Lhbbis77s+xHgg0y68NWiyuVSJ/kAykeEG25q6k/aISY+3xh19c8wgZ9vE06POvI8GZRwSxrSKX+lapsSk+k/4yjI=
  file: dist/*
  on:
    repo: pckilgore/heartless
    branch: release
